spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/books-mongo-dev?safe=true&journal=true&w=majority&connectTimeoutMS=1001&wtimeoutMS=1000&serverSelectionTimeoutMS=10000
  mail:
    port: 3026    # Must match the value specified in the SignUpNotificationServiceTest. Set hight to avoid problems on Unix envs

  boot:
    admin:
      client:
        url: http://localhost:8888
        username: testuser
        password: testpass
        instance:
          service-base-url: http://localhost:9000/
          metadata:
            tags:
              environment: mongo-java-server

# By default actuator is disabled.
# These values are overriden here to values that could be used on production
management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        # Exposing only read only items and not large data amounts - so no heapdump or shutdown. No project use of flyway, integrationgraph, liquibase, prometheus
        include: auditevents, beans, caches, conditions, configprops, env, health, httptrace, info, jolokia, logfile, loggers, metrics, mappings, scheduledtasks, sessions
  info:
    env:
      enabled: true
    git:
      mode: full
  health:
    mail:
      enabled: false

# With this profile we dont want any warning messages when the application cannot contact a Spring Boot Admin isntance at start up
logging:
  level:
    de:
      codecentric:
        boot:
          admin:
            client:
              registration:
                ApplicationRegistrator: ERROR


books:
  autoAuthUser: false

  client:
    enableCORS: true      # Note - this value overriden in the IntegrationTest base test class
    allowedCorsOrigin: http://localhost:9000
    postLogonUrl: http://localhost:9000/
    xsrfHeader: X-XSRF

  google:
    books:
      api:
        searchUrl: http://localhost:${wiremock.server.port}/books/v1/volumes?q=
        getByIdUrl: http://localhost:${wiremock.server.port}/books/v1/volumes/
        countryCode: country=GB
        maxResults: maxResults=30
        connectTimeout: 500
        readTimeout: 750

  reload:
    development:
      data: true    # Whether the contents of the /src/main/resources/sample_data will be reloaded into the database at application startup. Deletes all existing data!!!

  users:
    default:
      admin:
        email: "exmaple@example.com"  # The remote email address for the user that will be automatically made an admin on first logon
    registrationAdminEmail:
      enabled: false
      emailFrom: "exampleFrom@example.com"
      emailTo: "exampleTo@example.com"

    allow:
      actuator:
        user:
          creation: true

  jwt:
    # Can be set using com.aidanwhiteley.books.controller.jwt.JwtUtils::createRandomBase64EncodedSecretKey
    secretKey: wMYg4eYtigrQRSrqpI4ugQbK6BwutoAzXZ5jmK4nrybeOYkMbJrScOHmMQvld0RjHWWfyCx+foRk2lL7XbGQMA==
    cookieOverHttpsOnly: false
    cookieAccessedByHttpOnly: true

  oauth2:
    cookieOverHttpsOnly: false

