# Docker file for the MongoDB tier used by the Books Microservice
#
# This Dockerfile builds an image that will load sample books data and also
# some sample users.
#
# To build the Docker image use:
# docker build --rm -f Dockerfile-demodata -t aidanwhiteley/books-db-mongodb-demodata:5.0.30-focal .
#
# To run the Dockerfile created image use something like:
# docker run -e MONGO_INITDB_APP_USERNAME=abc -e MONGO_INITDB_APP_PASSWORD=def -e MONGO_INITDB_DATABASE=ghi aidanwhiteley/books-db-mongodb-demodata
#
# The Dockerfile created image is expected to be run from a docker-compose that sets the environment variables
# and is also in control of setting the overall MongoDb authorisation settings i.e. requiring authorisation!
#
FROM mongo:5.0.30-focal
COPY db_init/*.js /docker-entrypoint-initdb.d/
COPY db_init/*.sh /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/addUserFromEnvVar.sh